---
content_curation_prefix: content-curation
content_curation_git_branch: unicef_demo
content_curation_port: 8008
content_curation_server_pid_file: /tmp/content_curation_gunicorn.pid

content_curation_virtualenv: /var/www/content_curation_virtualenv
python_binary: "{{ content_curation_virtualenv }}/bin/python"
pip_binary: "{{ content_curation_virtualenv }}/bin/pip"
gunicorn_binary: "{{ content_curation_virtualenv }}/bin/gunicorn"

system_packages_to_remove: []

system_packages:
  - nginx
  - openssl

python_packages:
  - gunicorn
